env:
  browser: true
  es2021: true
extends:
  - xo
  - 'plugin:jest/recommended'
  - 'plugin:jest/style'
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
  - jest
rules:
  indent: [error, 2]
  prettier/prettier: error
  arrow-parens: [error, always]
